defaults:
  - callbacks: default
  - datamodule: cifar
  - logger: tensorboard
  - model: diffusion
  - trainer: default
  - paths: default
  - _self_

load_model: False
load_version_num: 0
dataset_choice: "MNIST"
